apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: abp.vnext.hello-secretstore
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: ./components/eshop-secretstore.json