apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: abp.vnext.hello-statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"