kind: ConfigMap
apiVersion: v1
metadata:
  name: abp-vnext-hello-ids4-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: abp-vnext-hello-ids4
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  SeqServerUrl: http://seq
  ConnectionStrings__Default=Server: mysql-db;database=Abp.VNext.Hello;UID=root;password=zxcvbnm; SSLMode=none
  BlazorClientUrlExternal: http://{{ .Values.externalDnsNameOrIP}}:30000
  BasketApiUrlExternal: http://{{ .Values.externalDnsNameOrIP}}:30005
  OrderingApiUrlExternal: http://{{ .Values.externalDnsNameOrIP}}:30002
  ShoppingAggregatorApiUrlExternal: http://{{ .Values.externalDnsNameOrIP}}:30006
  Redis__Config: redis,password=e$h0p0nD@pr,abortConnect=false
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: abp-vnext-hello-ids4
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: abp-vnext-hello-ids4
spec:
  replicas: 1
  selector:
    matchLabels:
      service: abp-vnext-hello-ids4
  template:
    metadata:
      labels:
        app: abp-hello
        service: abp-vnext-hello-ids4
    spec:
      containers:
        - name: abp-vnext-hello-ids4-api
          image: wjkhappy14/abp.vnext.hello.ids4:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: abp-vnext-hello-ids4-cm

---

kind: Service
apiVersion: v1
metadata:
  name: abp-vnext-hello-ids4
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: abp-vnext-hello-ids4
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31008
      protocol: TCP
      name: http
  selector:
    service: abp-vnext-hello-ids4
