kind: ConfigMap
apiVersion: v1
metadata:
  name: abp-vnext-hello-web-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: abp-vnext-hello-web
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  ApiGatewayUrlExternal: http://{{ .Values.externalDnsNameOrIP}}:30050
  IdentityUrlExternal: http://{{ .Values.externalDnsNameOrIP}}:30008

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: abp-vnext-hello-web
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: abp-vnext-hello-web
spec:
  replicas: 1
  selector:
    matchLabels:
      service: abp-vnext-hello-web
  template:
    metadata:
      labels:
        app: abp-hello
        service: abp-vnext-hello-web
    spec:
      containers:
        - name: abp-vnext-hello-web
          image: wjkhappy14/abp.vnext.hello.web:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: abp-vnext-hello-web-cm

---

kind: Service
apiVersion: v1
metadata:
  name: abp-vnext-hello-web
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: abp-vnext-hello-web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
      name: http
  selector:
    service: abp-vnext-hello-web
