kind: Deployment
apiVersion: apps/v1
metadata:
  name: consul
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      service: consul
  template:
    metadata:
      labels:
        app: abp-hello
        service: consul
    spec:
      containers:
      - name: consul
        image: consul:alpine
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8500
            protocol: TCP

---

kind: Service
apiVersion: v1
metadata:
  name: consul
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: consul
spec:
  type: NodePort
  ports:
    - port: 8500
      targetPort: 8500
      nodePort: 31850
      protocol: TCP
      name: consul
  selector:
    service: consul
