kind: Deployment
apiVersion: apps/v1
metadata:
  name: consul
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      service: consul
  template:
    metadata:
      labels:
        app: abp-hello
        service: consul
    spec:
      containers:
      - name: consul
        image: consul:alpine
        imagePullPolicy: IfNotPresent
        args:
          - "--requirepass e$h0p0nD@pr"
        ports:
          - name: http
            containerPort: 6379
            protocol: TCP

---

kind: Service
apiVersion: v1
metadata:
  name: consul
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: consul
spec:
  type: NodePort
  ports:
    - port: 3079
      targetPort: 3079
      nodePort: 30179
      protocol: TCP
      name: consul
  selector:
    service: consul
