kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: grafana
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  IdentityUrl: http://identity-api
  IdentityUrlExternal: http://{{ .Values.externalDnsNameOrIP}}:30008
  SeqServerUrl: http://seq
  SqlConnectionString: Server=sqldata;Database=Microsoft.abp-helloOnDapr.Services.grafanaDb;User Id=sa;Password=Pass@word

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      service: grafana
  template:
    metadata:
      labels:
        app: abp-hello
        service: grafana
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "grafana-api"
        dapr.io/app-port: "80"
        dapr.io/config: "dapr-config"
        dapr.io/log-as-json: "true"
    spec:
      containers:
        - name: grafana-api
          image: wjkhappy14/grafana.api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: grafana-cm

---

apiVersion: v1
kind: Service
metadata:
  name: grafana-api
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: grafana
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31002
      protocol: TCP
      name: http
  selector:
    service: grafana
