kind: Deployment
apiVersion: apps/v1
metadata:
  name: harbor
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: harbor
  template:
    metadata:
      labels:
        app: abp-hello
        service: harbor
    spec:
      containers:
      - name: redis
        image: redis:alpine
        imagePullPolicy: IfNotPresent
        args:
          - "--requirepass e$h0p0nD@pr"
        ports:
          - name: http
            containerPort: 6379
            protocol: TCP

---

kind: Service
apiVersion: v1
metadata:
  name: harbor
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: harbor
spec:
  type: NodePort
  ports:
    - port: 3379
      targetPort: 3379
      nodePort: 3379
      protocol: TCP
      name: harbor
  selector:
    service: harbor
