kind: ConfigMap
apiVersion: v1
metadata:
  name: ingress-nginx-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: ingress-nginx
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  SeqServerUrl: http://seq

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: ingress-nginx
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ingress-nginx
  template:
    metadata:
      labels:
        app: abp-hello
        service: ingress-nginx
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "ingress-nginx-api"
        dapr.io/app-port: "80"
        dapr.io/config: "dapr-config"
        dapr.io/log-as-json: "true"
    spec:
      containers:
        - name: ingress-nginx-api
          image: wjkhappy14/ingress-nginx.api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: ingress-nginx-cm

---

apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-api
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: ingress-nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31004
      protocol: TCP
      name: http
  selector:
    service: ingress-nginx
