kind: Deployment
apiVersion: apps/v1
metadata:
  name: metrics
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: metrics
  template:
    metadata:
      labels:
        app: abp-hello
        service: metrics
    spec:
      containers:
      - name: metrics
        image: metrics:alpine
        imagePullPolicy: IfNotPresent
        args:
          - "--requirepass e$h0p0nD@pr"
        ports:
          - name: http
            containerPort: 6379
            protocol: TCP

---

kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: metrics
spec:
  type: NodePort
  ports:
    - port: 33313
      targetPort: 33313
      nodePort: 33313
      protocol: TCP
      name: metrics
  selector:
    service: metrics
