kind: Deployment
apiVersion: apps/v1
metadata:
  name: minio
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      service: minio
  template:
    metadata:
      labels:
        app: abp-hello
        service: minio
    spec:
      containers:
      - name: minio
        image: minio:alpine
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 9000
            protocol: TCP

---

kind: Service
apiVersion: v1
metadata:
  name: minio
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: minio
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30900
      protocol: TCP
      name: minio
  selector:
    service: minio
