apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abp-hello
      service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: abp-hello
        service: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: zxcvbnm
        ports:
        - containerPort: 3306
          protocol: TCP
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: mysql
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 31306
      protocol: TCP
  selector:
    service: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

