kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: prometheus
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  IdentityUrlExternal: http://{{ .Values.externalDnsNameOrIP}}:30008

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: prometheus
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      service: prometheus
  template:
    metadata:
      labels:
        app: abp-hello
        service: prometheus
    spec:
      containers:
        - name: prometheus
          image: bitnami/prometheus:latest:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: prometheus-cm

---

kind: Service
apiVersion: v1
metadata:
  name: blazor-client
  namespace: {{ .Values.namespace }}
  labels:
    app: abp-hello
    service: prometheus
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
      protocol: TCP
      name: http
  selector:
    service: prometheus
