apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: abp-hello-statestore
  namespace: {{ .Values.namespace }}
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    secretKeyRef:
      name: abp-hellosecrets
      key: redisPassword
  - name: actorStateStore
    value: "true"
auth:
  secretStore: kubernetes