apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sendmail
  namespace: {{ .Values.namespace }}
spec:
  type: bindings.twilio.sendgrid
  version: v1
  metadata:
  - name: apiKey
    value: "replace-with-your-sendgrid-api-key"